development:
  clients: &development_clients
    default:
      database: catdogmanbearpig_development
      hosts:
        - localhost:27017
  sessions:
    <<: *development_clients

test:
  clients: &test_clients
    default:
      database: catdogmanbearpig_test
      hosts:
        - localhost:27017
  sessions:
    <<: *test_clients
